### ISSUE TITLE
Show WOT on app result screen

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#10]
Currently WOT is absent on app results screen. This is useful info to know before investigating an app in detailed app view. 

![image](https://github.com/zapstore/zapstore/assets/64376233/dc5f1cac-bafc-4599-b34a-6c2b0757f2c4)

**Comment by alltheseas** [comment]
@NielLiesmons @franzaps is it possible to surface WOT on app search results?

**Comment by franzaps** [comment]
At some point (when we open the floodgates) we'll definitely have to because spam. I'm very proud of my little WoT API handling a massive amount of keys in a graph... but it will be hitting its limits soon as we heavily rely on it

**Comment by franzaps** [comment]
Leaving this for a latest release when further work done on https://github.com/zapstore/trustgraph

**Comment by franzaps** [comment]
Will reopen later with a more specific description once we rethink how to do WoT in results, etc
