### ISSUE TITLE
display my WOT's user verified hash of an app

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#102]
## user story

As a ZS user who is shopping for an app, I would like to see who (if anyone) from my WOT has verified a particular app's sha256, so that I can have greater confidence ZS is not rugpulling me.

### acceptance criteria
1. ZS displays npub WOT's hash verifications visually (e.g. alice, bob, carla have all validated a particular app)

### context

This is similar visually to alice, bob, carla follow a particular npub

**Comment by franzaps** [comment]
Adding to my comment [here](https://github.com/zapstore/zapstore/issues/101#issuecomment-2166928011) I don't think this makes sense. If zap.store were to be malicious, it could also fake "(if anyone) from my WOT has verified a particular app's sha256". So there's zero gain, more complex UI, and more work.

Feel free to reopen if there's a better argument
