### ISSUE TITLE
Do not let feedback submitter send empty message + feedback rubric

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#104]
Suggestion:

Add rubric/template:

_OS & Device_
E.g. android 14 samsung X

_what happens_
E.g. When I download app X, ZS crashes my OS

_steps to recreate_

1. Open zap store
2. Action x
3. Action y 
4. etc..

_link to screenshot_

_what do i think should happen_

**Comment by franzaps** [comment]
Unify with #37
