### ISSUE TITLE
Missing flutter_data (build from source)

### ISSUE THREAD

**Issue by vitorpamplona** [zapstore/zapstore#107]
Need to send the `flutter_data` dir to github

```
> flutter pub get
Resolving dependencies... 
Because zapstore depends on flutter_data from path which doesn't exist (could not find package flutter_data at "../flutter_data"), version solving failed.
```

**Comment by armanism** [comment]
And purplebase

**Comment by alltheseas** [comment]
@vitorpamplona what is this needed for? Setting up, so that you can sign e.g. Amethyst APK?

**Comment by armanism** [comment]
> @vitorpamplona what is this needed for? Setting up, so that you can sign e.g. Amethyst APK?

To build from source https://github.com/zapstore/zapstore?tab=readme-ov-file#build-from-source

**Comment by franzaps** [comment]
100% will fix this on next release
