### ISSUE TITLE
Download on ZapStore Logo!

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#108]
Download on ZapStore logo is needed! This logo can be added by devs to their websites.

How might we design an AWESOME ZS logo that highlights ZS uniqueness?
1. Is it possible to highlight in a logo that users can zap others on ZS?
2. Is it possible to highlight in a logo that users can see which apps their friends use?

Examples:
-download on AppStore
![Screenshot from 2024-06-21 07-46-54](https://github.com/zapstore/zapstore/assets/64376233/c2b57dc8-88a1-4ecd-a6ae-42d034e27146)

-download on google play store

![Screenshot from 2024-06-21 07-47-43](https://github.com/zapstore/zapstore/assets/64376233/f239dbd3-0d9a-4549-9973-43b94cddd4cb)
![Screenshot from 2024-06-21 07-47-54](https://github.com/zapstore/zapstore/assets/64376233/ec62de5c-0dbd-48dc-abeb-e361ba0ab0b7)

-download APK
![Screenshot from 2024-06-21 07-46-44](https://github.com/zapstore/zapstore/assets/64376233/f8c4ab7d-65e1-4b8d-acf7-2b67d928fa44)

-download F-droid
![Screenshot from 2024-06-21 07-48-43](https://github.com/zapstore/zapstore/assets/64376233/19d2d14a-6ebe-4cf6-af08-8709de726812)

@NielLiesmons

**Comment by alltheseas** [comment]
@franzaps suggests

> zap the app on zap store

**Comment by alltheseas** [comment]
A fresh perspective that ZS can surface is that one can "zap the dev" on ZS - see related prompt to zap on app update https://github.com/zapstore/zapstore/issues/70#issuecomment-2150955514


I wonder if zapping the dev scales beyond the current setup where everyone knows everyone on nostr

**Comment by alltheseas** [comment]
Might we have a customizable download button? 

For instance gigi can create a "download ZS" button that has a graphic equivalent of "gigi recommends this"/"recommended by" + pfp

**Comment by franzaps** [comment]
@alltheseas yes we could generate these images on the fly... but won't these recommendations look cramped in such a button? Not sure

What are pros and cons of "zap the app" vs "zap the dev", I tend to prefer the former but not sure why

**Comment by alltheseas** [comment]
Everyone knows the app, not everyone knows the dev(s) (at scale).

Zap the dev is more human, emotional.

**Comment by alltheseas** [comment]
> but won't these recommendations look cramped in such a button? Not sure

There can be different size buttons, banners. This is design magic territory

**Comment by franzaps** [comment]
> Everyone knows the app, not everyone knows the dev(s) (at scale).
> 
> Zap the dev is more human, emotional.

Following our chat today, I'm thinking "zap the devs" could be appropriate language when zapping a release to which several devs could have contributed

**Comment by itstomekk** [comment]
These type of buttons?

![image](https://github.com/user-attachments/assets/81be909a-5d20-40d9-84d0-7fc6672fba40)
![image](https://github.com/user-attachments/assets/32fba27b-baf5-4191-8697-1ffdc83020c9)
![image](https://github.com/user-attachments/assets/a7b89854-830b-43a4-95de-a031bf4b2a96)

**Comment by itstomekk** [comment]
here are the files with .psd if anyone is interested in building on this:   

https://drive.google.com/drive/folders/16hzX0wpFOvFDJNuYkWzruiz0fuIVG95j?usp=sharing

**Comment by franzaps** [comment]
This is great, thank you @itstomekk ! 

I will add these to our design kit

**Comment by alltheseas** [comment]
@NielLiesmons can you update ser with zapstore.dev website (old one has zap.store website)?
