### ISSUE TITLE
Web of trust default to franzap/zs when user logged out

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#11]
So that I can demo the app right away, start in logged in as fran@zap.store, and clearly display "logged in as fran@zap.store". 

Add a method to log in as other npub.

**Comment by franzaps** [comment]
Not sure I like this. Is logging in a big deal? All other nostr apps do

**Comment by franzaps** [comment]
Instead we could offer to view franzaps WoT _when showing the web of trust widget_ and user is logged out and doesn't want to log in.
