### ISSUE TITLE
Problems with the app

### ISSUE THREAD

**Issue by talha5758** [zapstore/zapstore#118]
The app is freezing a lot even though my device has snapdragon 888, there's no actual options section for some reason, no shizuku and material you support (the second one ain't that important but it would be cool), packages can only be installed when passed to another page other than the downloads section. Also F-Droid and other repos' support would be a great addition besides using just Github.

**Comment by franzaps** [comment]
Thanks for reporting, and sorry that it's freezing for you. Unfortunately we don't have much resources yet to test on more devices.

More sources are coming soon.

**Comment by franzaps** [comment]
Will be testing and fixing via #93
