### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by xjmzx** [zapstore/zapstore#119]
Android 11 fails to load or search.
OxygeneOS 11.1.2.2
Oneplus Snapdragon 845
RAM 8G

![Screenshot_20240728-111531](https://github.com/user-attachments/assets/cb525855-da3c-46cd-bad9-07fdab873be9)

**Comment by franzaps** [comment]
Thanks for reporting @xjmzx , I can't reproduce but attempting a fix
