### ISSUE TITLE
Allow multiple log-ins

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#12]
_what happens currently_

I can log in as a single user - e.g. fran@zap.store

_what I would like to do_

I would like to do log in as a few different users simultaneously, so that I can combine the WOT for extra signal.

**Comment by franzaps** [comment]
Sounds complicated and not sure if worth the benefit, open to discuss. What could be done is make the WOT API accept multiple inputs for a web of trust calculation, but those queries might take even longer which hurts UX

**Comment by alltheseas** [comment]
> Sounds complicated and not sure if worth the benefit, open to discuss. What could be done is make the WOT API accept multiple inputs for a web of trust calculation, but those queries might take even longer which hurts UX

Just a thought I had as I was logging in today. Probably a not useful feature. 

I did notice WOT calc takes time.
