### ISSUE TITLE
Phone Freezes when Using the App

### ISSUE THREAD

**Issue by Godrigos** [zapstore/zapstore#121]
Hi there. I got a wierd error using the app. I also use Florisboard as keyboard, when I tapped the search field, before the keyboard pops up my phone froze completely, had to hard reset it. Before needing the keyboard the app was fine. Got the same behavior twice.
I wasn't capable to find any log to share. Maybe because of the hard reset after freeze.

UPDATE: It still freezes, but take much longer. Mullvad problably is not the cause but modifies something related to it...

**Comment by alltheseas** [comment]
Which device? Which OS?

**Comment by Godrigos** [comment]
Android 14 - Motorola Edge 50 Pro.

**Comment by alltheseas** [comment]
Did you report this bug to florisboard? 

As far as I'm aware no stock android or grapheneOS keyboard issues have been reported to zapstore

**Comment by Godrigos** [comment]
Never thought about doing it, since it works on every other app I have installed. But I might do so.

**Comment by alltheseas** [comment]
@patrickgold have yall seen this Florisboard behavior in other situations?

**Comment by patrickgold** [comment]
No, we have never seen such a behavior where the whole system crashes.

@Godrigos can you please provide more info:
1. By "hard reset" I assume you mean force shutdown the system with the power button?
2. Which FlorisBoard version are you on?
3. Where did you get this APK from?

**Comment by Godrigos** [comment]
1.  No, I had to hold volume down and power button to enter recovery mode and reboot from there. The power button alone was also unresponsive.
2. Version 0.3.16 (86)
3. Got it from https://github.com/florisboard/florisboard using [Obtainum](https://github.com/ImranR98/Obtainium) to install.

I think I might only go back to stock keyboard.
Thanks for the attention and patience.

**Comment by Godrigos** [comment]
**UPDATE: I might be misleading you guys.**
I remove florisboard, normaly rebooted the phone, and even so it froze. I took more time, I was able to navigate a little bit more throught the app, even it was unresponsive from time to time, till it finally froze the device completely.
This phone has Think Shield for Mobile, a security stuff from Lenovo (don't know if it can have something to do with it).

This time  force shutdown the system with the power button worked.

**Comment by alltheseas** [comment]
>  Think Shield for Mobile, a security stuff from Lenovo (don't know if it can have something to do with it)

Can you disable, and observe the zap store behavior?

**Comment by Godrigos** [comment]
It can't be disabled, it seems to be a hardware component. There is no option to disable it.

> >  Think Shield for Mobile, a security stuff from Lenovo (don't know if it can have something to do with it)
> 
> Can you disable, and observe the zap store behavior?
> 
>

**Comment by patrickgold** [comment]
Thanks a lot for the details, so we can assume that it isn't FlorisBoard's fault but something else?

**Comment by alltheseas** [comment]
> Thanks a lot for the details, so we can assume that it isn't FlorisBoard's fault but something else?

That's what I'm reading from the user's report. Thank you @patrickgold for the quick response irregardless 🙏. 

Unrelated to the issue above @patrickgold would you be willing to test out Zap.Store's dev APK nostr signing flow with your app? 

Beyond dev APK signatures (which reduce trust necessary in a central appstore authority), the ZS team is working on 1) enabling devs to easily communicate with their respective app's community, and 2) a permissionless method for users to directly pay FOSS app devs as a token of appreciation for the value created.

**Comment by Godrigos** [comment]
> Thanks a lot for the details, so we can assume that it isn't FlorisBoard's fault but something else?


Yes.

**Comment by Godrigos** [comment]
I might have discovered what is causing conflict. The freezes and crashes stop if I disable mullvad vpn. I have their app instslled. When it is active, a few seconds after opening zap.store, the fone freezes. I disabled it and was capable of using the app normally for several minutes.

**Comment by franzaps** [comment]
@Godrigos any updates on this? Is it still happening? Does Mullvad with other apps cause freezes too?

There is nothing special between Mullvad and zap.store. 

I will be releasing an update in the next week or so with lot of focus on performance, maybe that helps

**Comment by Godrigos** [comment]
Not much to add. No other app chases when using Mullvad, it seems something related to intermet connection. Once using VPN loading stuff takes longer and the app chrashes faster.
I noticed something. I was experimenting and I got a similar behavior using Aurora Store, it doesn't crashes. But hangs an take a lot of time to load stuff.
Does zap.store has something in common with Aurora, the design seems to have common origin (framework maybe).

**Comment by Godrigos** [comment]
> @Godrigos any updates on this? Is it still happening? Does Mullvad with other apps cause freezes too?
> 
> There is nothing special between Mullvad and zap.store. 
> 
> I will be releasing an update in the next week or so with lot of focus on performance, maybe that helps

Installed the new version. Working like a charm. No crashes or hangs. Installed apps smoothly.
Thank you very much for all the effort.

**Comment by franzaps** [comment]
Fantastic to hear that, thank you for reporting @Godrigos !
