### ISSUE TITLE
detect and auto-suggest to update to latest ZS version

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#128]
-detect if ZS is running an older version
-through some UI element (e.g. toast etc) ask if user wants to update to latest ZS version from current version

**Comment by alltheseas** [comment]
related: #75

**Comment by alltheseas** [comment]
I was testing an older ZS version, and I didnt realize it

**Comment by franzaps** [comment]
Will add a one-time toast when a new zap.store version is available. If dismissed, it won't show up again and user can update app like any other (via the updates screen)

**Comment by franzaps** [comment]
Fixed a few commits ago
