### ISSUE TITLE
Suggest someone else's app for addition to zap.store

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#13]
## user story

As a zap.store enthusiast, I would like to submit another dev's app to zap.store, so that the zap.store app library becomes more valuable for me and others.

### acceptance criteria

1. there is a method to suggest an app to zap.store
2. required field: provide repo where APK can be found
3. optional field: provide repo where SHA256 can be found

**Comment by franzaps** [comment]
Let's just leave this to socials, people can hit me up on nostr and I'll add the repo to the queue.

Supported right now:
 - github repos having a latest release with an APK file

Next week I'll publish the releastr repo to track source support, I want to add websites (to pull things like Signal and Mullvad), gitlab and codeberg. And a checker to reject (or ask for confirmation) F-Droid signed APKs

**Comment by alltheseas** [comment]
I'll add a note to readme to reflect

**Comment by alltheseas** [comment]
https://github.com/zapstore/zapstore/issues/43

https://github.com/zapstore/zapstore/issues/44

https://github.com/zapstore/zapstore/issues/42
