### ISSUE TITLE
Pop! OS app store 

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#135]
https://pop.system76.com/

**Comment by alltheseas** [comment]
related to https://github.com/zapstore/zapstore/issues/133

**Comment by franzaps** [comment]
I like the idea but what are we going to put there?

**Comment by alltheseas** [comment]
Let's discuss as an exploratory thing. Maybe there is a ZS powered nostr API. "Upgrade your appstore with nostr. Powered by ZS".  I'll move to the backlog

**Comment by alltheseas** [comment]
https://github.com/zapstore/backlog/issues/2
