### ISSUE TITLE
issues with appverifier not able to install or update apps

### ISSUE THREAD

**Issue by tjaynl** [zapstore/zapstore#138]
So the install/update option doesn't work if you have appverifier installed, because as soon as you close the appverifier it closes the zap.store app aswell.

**Comment by franzaps** [comment]
Can you share a bit more on how you got to that conclusion? I have both zap.store and AppVerifier, I closed AppVerifier and zap.store had no issues installing a new app.

What OS are you on?

**Comment by tjaynl** [comment]
I'm using Android 14, zap.store 0.1.3

It starts up appverifier but I only get the default android key below, when I press the back key it closes the zap.store for me. Then when I open up the zap.store again it asks me to update or install the app again as in looping so it doesn't go through with the installation or update and keeps looping.

**Comment by franzaps** [comment]
I'm trying hard to understand, but I can't, sorry! Who starts up AppVerifier? Are you launching AppVerifier from zap.store? Which key, and which back key? Would you mind recording what you see?

**Comment by franzaps** [comment]
do you mind sharing a screen capture or screenshot?

**Comment by franzaps** [comment]
Closing for now
