### ISSUE TITLE
Add "or your npub" in login textfield

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#146]
_what happens_

In the login box, current suggestion of "your nip05" can be confusing to newbies, as not everyone has a nip-05. 

_suggestion_

nip-05 remains niche. Whereas everyone has a npub. Suggest adding "or npub" to the login input box

![image](https://github.com/user-attachments/assets/f928bad5-f146-4522-b50c-e56b0b01e7bb)

**Comment by alltheseas** [comment]
via confused customer

https://njump.me/nevent1qvzqqqqqqypzqt6jkx07zsy0d8hqayy7mr72cyuvtumscpw7yncdsdc2mfuh2gerqqsyv7ug7txkdwyrjwwwdpszte7kk46af248jl0e8zq36emuvz9utvchvzmeq

**Comment by franzaps** [comment]
Agreed
