### ISSUE TITLE
(Less) cold start - do not require search to show first app results

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#15]
_what happens_

In order to see any apps, I must first:

1) sign in (see #11 demo mode), and
2) search.

_suggestion_

Is it possible to surface apps without having to search (step 2) above?

### design

How might this look like @NielLiesmons ?

### builds on / related to 

#11 

Feedback by @gzuuus

https://njump.me/note18t3h5q23llzjqxue4x0sxvnx8pprv73cuwynrp3fl7rt6z303kssv6tt5p

**Comment by franzaps** [comment]
Related feedback

 - Interesting appstore so far looks good 👌 but a homepage is urgently needed 
 - list of all the apps? 
 - i have no idea what ai am doing on the home button. needs better ux. i dont know what to look for 
 - This looks very promising, great work. My request: I would like to be able to browse the entire app catalog without having to search
 - It would be nice to be able to see all apps and have categories as the amount of available apps increases. 
 - how do we discover new apps?

**Comment by franzaps** [comment]
I think we should manually curate some popular/quality apps for now

**Comment by franzaps** [comment]
Logging in was never a requirement to search!  Related to this is #48 , so updating #11 and closing here

**Comment by alltheseas** [comment]
> think we should manually curate some popular/quality apps for now

Agree

> Logging in was never a requirement to  search! 

Correct! The point of this issue is to have something on the main page before user searches anything.
