### ISSUE TITLE
About the new update

### ISSUE THREAD

**Issue by talha5758** [zapstore/zapstore#158]
The app looks very clean and nice right now, do you think adding support for 90 hz and 120 hz screens?
Also a category section would be great.

**Comment by franzaps** [comment]
Thank you! What do you mean by adding support, it doesn't work on those screens?

**Comment by talha5758** [comment]
It works but not at the desired refresh refresh rate by the screens.

**Comment by franzaps** [comment]
But is it buggy? I really am not sure what can be done. Can you share a screencap?

**Comment by talha5758** [comment]
Can I show it tomorrow, it's pretty late here, it's not buggy by the way, the app can't go beyond 60hz even though my phone set the hz to 120 hz for the app.

**Comment by talha5758** [comment]
> Can I show it tomorrow, it's pretty late here, it's not buggy by the way, the app can't go beyond 60hz even though my phone set the hz to 120 hz for the app.
> (Nevermind, I guess it was the fault of my software, it is locked to 120hz now when I set it manually) 

...

**Comment by talha5758** [comment]
You can close the issue I guess, though I must say there's lags when clicking on app pages for about a second or two.

**Comment by franzaps** [comment]
Is the lag due to the screen refresh rate? Not sure about that. I'll close here but reopen another one about the lag, esp if you can get a screencap. Thanks
