### ISSUE TITLE
Clear search UI

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#16]
_what happens_

When I enter a search term, and I receive results, after I clear the search box nothing happens. Search results remain.

After I hit the home button, nothing happens Search results remain.

_Suggestion_

Consider clearing search results. 

_Design_

What's the expected pattern here @NielLiesmons ?

![zapstore1 (1)](https://github.com/zapstore/zapstore/assets/64376233/acf03091-4ede-4b4a-b784-371953447c11)

![zapstore2](https://github.com/zapstore/zapstore/assets/64376233/4b40aefc-f535-41ab-8258-9bbd730253dc)

**Comment by franzaps** [comment]
Fixed in f32fc35
