### ISSUE TITLE
filter out apps not compatible with device

### ISSUE THREAD

**Issue by yojimble** [zapstore/zapstore#176]
it's frustrating to wait an age for an app to download and verify only for it not to install

**Comment by alltheseas** [comment]
@yojimble which device, OS, and which app(s)?

**Comment by franzaps** [comment]
@yojimble Please update to the latest 0.1.6 and try again:

https://zapstore.dev/download

The 0xchat issue was fixed. Reopen if it still does not work.

**Comment by yojimble** [comment]
YEAH! all fixed, cheers

**Comment by yojimble** [comment]
well I spoke too soon, the app opens at least but update date buttons dont respond

**Comment by franzaps** [comment]
Sorry, what do you mean by "don't respond"? You tap on Update and nothing happens, even after waiting a bit? Does this happen for all apps? Please provide a bit more detail

**Comment by yojimble** [comment]
yes nothing happens at all

so for example tapping this update button doesnt do anything
![WhatsApp Image 2024-12-09 at 12 53 46 PM](https://github.com/user-attachments/assets/4c926672-5b9f-4bf5-a4bb-20191da20f8b)

if I click the app logo this page opens, but that update button is also unresponsive
![WhatsApp Image 2024-12-09 at 12 53 53 PM](https://github.com/user-attachments/assets/2ff3c4e2-80c0-4ab1-8b31-d36d60295079)

I think for all apps but cannot test any others right now as the spinning lightning bolt is back so the app is not opening again

**Comment by franzaps** [comment]
@yojimble Thank you for the screenshots! Very helpful. I added a few guards on version 0.1.7, so if this is a loading issue you should see a spinner now, and if it's an actual error a toast with more information.

Would you mind installing the latest APK from here: https://zapstore.dev/download

**Comment by yojimble** [comment]
update buttons are working!
