### ISSUE TITLE
Multi-platform: Windows, BSD, Linux, macOS

### ISSUE THREAD

**Issue by jujubeja** [zapstore/zapstore#187]
ZapStore alternatives: Microsoft Store, steam

ZapStore alternatives: GNOME Software, AUR

ZapStore alternatives: BSD pkg, freshports

ZapStore alternatives: Mac App Store

Cross-platform requires the use of other programming languages ​​such as zig, which can write GUI and backend 
https://github.com/ziglang/zig

**Comment by franzaps** [comment]
Yes, it's planned! https://github.com/zapstore/zapstore/issues/29

Linux later on.

Flutter, not zig.
