### ISSUE TITLE
Landing page for developers

### ISSUE THREAD

**Issue by franzaps** [zapstore/zapstore#2]
Different options will be offered in order for them to verify their apps on zap.store:
 - signing up for DM reminders of "hey you just made a release, sign your app/release/metadata" by visiting this website or using this CLI tool (active)
 - if using Github, integrate a Github action that takes either an nsec or connects to a bunker with an auth token (set and forget)
 - sign a NIP-69 linking their PGP key or APK certificate (set and forget), used in combination with the delegation tags (`p`/`zap`)

**Comment by alltheseas** [comment]
Splitting into three separate issues: 


- [ ] signing up for DM reminders of "hey you just made a release, sign your app/release/metadata" by visiting this website or using this CLI tool (active) https://github.com/zapstore/zapstore/issues/5
- [ ] if using Github, integrate a Github action that takes either an nsec or connects to a bunker with an auth token (set and forget)
- [ ] sign a NIP-69 linking their PGP key or APK certificate (set and forget), used in combination with the delegation tags (p/zap)

**Comment by franzaps** [comment]
https://zap.store/developers

kind of a shit page but gets the job done for now
