### ISSUE TITLE
Please document all protocol aspects of the app

### ISSUE THREAD

**Issue by Giszmo** [zapstore/zapstore#25]
Building on nostr means to be interoperable but I can't find which kinds of events are being used here.

I ask because I maintain the probably biggest repository of Bitcoin wallet apps at WalletScrutiny.com where we also recently started to add ratings for apps and I  would like to have synergy between the two projects as early as possible.

**Comment by franzaps** [comment]
Sure! Here are some sample events so you get an idea of what we're using: https://github.com/zapstore/zapstore/wiki/Sample-app-events

**Comment by Giszmo** [comment]
So you have:

* kind 1063: artifact event
  * url-tag links to binary artifact
  * x-tag hash of artifact
  * size-tag in bytes
  * p-tag: where does that come from? You set it manually? I saw you said you scraped github.
* kind 30063: release event
  * d-tag global app identifier @ version
  * url-tag links to github release
  * a-tag links to kind-32267 app event and kind-1063 artifact event(s?)
* kind 32267: Description of app
  * stuff describing the app except for an actual description

* Why are artifact events not replaceable with the hash as the d-tag? I imagine the need of adding further data or correcting data.
* Why does the artifact event not link to the git revision or the release event? With many artifacts matching the same release, it feels more logical to link from the artifact to the release and not list artifacts in the release event.
* The example app event uses `com.mutinywallet.mutinywallet` in its d-tag which is the Android App ID I assume. In WalletScrutiny I had decided to prefix this with `android/` to avoid ambiguity. I see you treat "Mutiny Wallet" as the app on all its platforms and with this app and the single code base that is ok but some apps are quite different depending on the platform.

**Comment by franzaps** [comment]
Artifact events are NIP-94, it's a non-replaceable event. If you need to correct data update your release pointing to another kind 1063.

Reverse-domain notation is the standard and recommended but it's not me who will be creating these events. It's up to developers. They are welcome to create multiple 32267 app events for different platforms if it's more convenient.
