### ISSUE TITLE
See npub WOT app usage

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#4]
## user story

As a ZapStore customer, I would like to be able to see which of my follows use an app, so that I can have greater confidence that this app is neither a scam nor has crap user experience. 

### acceptance criteria

1. Via web of trust show me which of my follows use an app

### implementation details

1. Customer can input their (or someone else's) nostr pubkey (npub)
2. Copypasta method
3. Nip-07 extension supported

**Comment by alltheseas** [comment]
0.1 shows which users *follow* a particular app npub. Is showing usage possible @franzaps ?

**Comment by franzaps** [comment]
For that we would need users signing messages saying "I use this app" (which I would never do automatically because of privacy implications). Anyway not possible yet, we need to integrate Amber which I think was scheduled for 0.2.0

**Comment by franzaps** [comment]
Need to rethink as part of more comprehensive WoT strategy
