### ISSUE TITLE
Write privacy policy

### ISSUE THREAD

**Issue by franzaps** [zapstore/zapstore#40]
Privacy is a fundamental value at zap.store . Any privacy issues are unintentional and due to lack of time not malice, we're not fucking Google

**Comment by alltheseas** [comment]
A few privacy questions:
1) does zap store know which npubs downlaod which apps?
2) does the app dev know which npubs download their app(s)?
3) does zapstore know the IP address of the users?
4) is any other information observable by zapstore?
5) what/is any information recorded by zapstore?
6) for how long?
7) in what ways does zapstore use relays?
8) does zapstore use its own relay?

**Comment by alltheseas** [comment]
Added draft based on above answers here: https://github.com/zapstore/.github/blob/main/PRIVACY.MD

**Comment by franzaps** [comment]
good enough for now!
