### ISSUE TITLE
Add categories of apps

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#48]
Can use github labels as a start, and also more consumer friendly appstore labels

Games: action, racing, strategy ...

Apps: entertainment, social networking, lifestyle, photo & video, education, health & fitness, productivity utilities, books, sports, music, business, graphics & design, navigation, reference, travel, news, finance, medical, weather...

**Comment by alltheseas** [comment]
Implementation wise should/could this use labels on nostr?

NIP-32 labeling https://github.com/nostr-protocol/nips/blob/master/32.md

**Comment by alltheseas** [comment]
<img width="309" alt="Screenshot 2024-05-11 at 10 30 36 PM" src="https://github.com/zapstore/zapstore/assets/64376233/4ebaf1a9-d4d2-4e9a-affd-528fd0692cab">

**Comment by franzaps** [comment]
https://image.nostr.build/fc3c1da29a2a916de177de2200ca025761d8ca30b1c7713d91eaf81793782d8c.png

@NielLiesmons we completely lost you?

**Comment by NielLiesmons** [comment]
Nope, finally finding time again to go through all this.

**Comment by franzaps** [comment]
Done
