### ISSUE TITLE
Prompt if app identifier has a different signature

### ISSUE THREAD

**Issue by franzaps** [zapstore/zapstore#59]
Updates work by querying the relay for an app identifier with a newer version. If the newer version artifact has a different certificate the upgrade will be rejected by Android, it would be great to gracefully handle the situation.

The likelihood of different signatures for same app id is non negligible (self-signed, F-Droid, Play Store).

Maybe we should index the certificate pubkey in the artifact? https://github.com/zapstore/indexer/issues/7

Down the line this would allow us to prompt the user to remove a dirty Play Store fiat install in favor of a pure, beautiful FOSS version.

**Comment by alltheseas** [comment]
> Prompt if app identifier has a different signature #59

Who is being prompted in case signatures dont match? 

Zapstore? App dev? User?

**Comment by franzaps** [comment]
zapstore will prompt/inform the user, user can choose to uninstall current app to prevent it being rejected by Android

**Comment by alltheseas** [comment]
> zapstore will prompt/inform the user, user can choose to uninstall current app to prevent it being rejected by Android

This is a technical matter. I am for giving the end user maximum visibility. 

Concurrently I wonder how might any of this be communicated in a 9th grade reading level? 

Should zapstore handle this in an "auto-pilot" way/under the hood?

**Comment by franzaps** [comment]
Actually it might be a useful tool to nudge people out of slave tech and into freedom tech

**Comment by franzaps** [comment]
https://github.com/zapstore/indexer/issues/7

**Comment by alltheseas** [comment]
if a normie reads this they will become confused

> " It appears you have a different version of this app, that you probably installed on Play Store. If you'd like to install the version on zap.store you need to remove the app first, make sure you back up all you data"

**Comment by franzaps** [comment]
> if a normie reads this they will become confused
> 
> > " It appears you have a different version of this app, that you probably installed on Play Store. If you'd like to install the version on zap.store you need to remove the app first, make sure you back up all you data"

How about "you're using slave tech. Remove that trash and install again using zap.store"

Jokes aside- what do you suggest? Not doing anything is a worse option because a signature mismatch will cause an update via zap.store to fail

**Comment by alltheseas** [comment]
I don't know if we can word it much simpler. I am wondering if there is some more automated way to 
1) uninstall the app
2) backup data
3) install via ZS

**Comment by franzaps** [comment]
@alltheseas I will check Android permissions but I really doubt it's possible. Also, there is no single way of backing up/restoring an app's data

**Comment by alltheseas** [comment]
on 0.1 robosats fails to upgrade to latest version. all other apps tested updated

**Comment by franzaps** [comment]
Pain in the ass. WIP

```dart
final bytes = hexToBytes(
      '30450a1d3afbd22c98d9d8e987df8c1fbc2d0c97be21930c3b4d73906b0890bb');
await AndroidPackageManager().hasSigningCertificate(
      packageName: 'org.package',
      certificateBytes: Uint8List.fromList(bytes),
      type: CertificateType.sha256);
```

```dart
final flags = PackageInfoFlags(
    {
      PMFlag.getMetaData,
        // Note: THIS IS REQUIRED if you need access to permissions
        // And the information is contained under `requestedPermissions`
        // instead of `permissions`
        PMFlag.getPermissions,
        PMFlag.getReceivers,
        PMFlag.getServices,
        PMFlag.getProviders,
      PMFlag.getSigningCertificates},
  );

  final info = await AndroidPackageManager()
      .getPackageInfo(packageName: 'org.package', flags: flags);
  info!.signingInfo!.signingCertificateHistory!.first;
 ```

**Comment by franzaps** [comment]
Implemented a check that happens when copying the package SHA-256 to the clipboard. If something's wrong there will be an error message.

I'll leave it there for testing and later on could reuse in some more useful way.

**Comment by franzaps** [comment]
Implemented in `packageCertificateMatches()` before updating
