### ISSUE TITLE
zap prepay a dev

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#64]
## user story

As a FOSS app supporter, I would like to zap a dev and see how long I am "subscribing" to their services, so that I can support the dev, and that I can see when/if I should be zapping the dev again.

### acceptance criteria
1. unless dev specifies, zap.store uses a default value (e.g. 15,000 sats) for a monthly "subscription" fee. if the user zaps a dev, they then get to see that they have supported the dev for X equivalent days
2. there is a daily updating countdown that states e.g. 21 days remaining of subscription (see mullvad example below) that is unique, and private to the user
3. the user has an option to top-up their pre-paid subscription

### example
see mullvad

![image 140](https://github.com/zapstore/zapstore/assets/64376233/618c4205-1047-4769-a13c-d64f83a80fab)

![Screenshot 2024-05-13 at 2 48 30 PM](https://github.com/zapstore/zapstore/assets/64376233/da6c40d4-c4f6-45cd-8a20-cbb23c520872)

### related
#47 
#39 
#61

**Comment by franzaps** [comment]
I love this idea but it's too far in the future, most apps don't even have subscriptions or have agreed to this model. Closing to revisit in the future.

**Comment by frnandu** [comment]
I also love this idea. Let's keep it in the horizon. With nwc should be achievable.
