### ISSUE TITLE
Not updating apps on LineageOS

### ISSUE THREAD

**Issue by franzaps** [zapstore/zapstore#73]
Anyone with LineageOS can reproduce?

(submitted via the app)

**Comment by franzaps** [comment]
> Does not update apps installed by other app stores on LineageOS

another message received

**Comment by alltheseas** [comment]
Which OS version? Which device?

**Comment by xjmzx** [comment]
LineageOS 21 / Android 14 updates apps no problem.

**Comment by alltheseas** [comment]
@xjmzx curious did you consider, and compare grapheneOS to LineageOS

**Comment by franzaps** [comment]
I would think most people using LineageOS is because they don't own a Pixel

**Comment by xjmzx** [comment]
> @xjmzx curious did you consider, and compare grapheneOS to LineageOS

I would like to try Graphene, no pixel.
Lineage seems to work well so far.

**Comment by franzaps** [comment]
Working for other LineageOS users too, closing for now
