### ISSUE TITLE
Check for memory leaks

### ISSUE THREAD

**Issue by franzaps** [zapstore/zapstore#74]
https://pub.dev/packages/leak_detector

**Comment by alltheseas** [comment]
This tool checks all apps?

**Comment by franzaps** [comment]
Just for zap.store

**Comment by franzaps** [comment]
Checked with DevTools, results pretty good

Found a bug that was fixed: https://njump.me/nevent1qvzqqqqqqypzqun2rcnpe3j8ge6ws2z789gm8wcnn056wu734n6fmjrgmwrp58q3qywhwumn8ghj7mn0wd68ytndw46xjmnewaskcmr9wshxxmmd9uq3wamnwvaz7tmjv4kxz7fwwpexjmtpdshxuet59uqzp7gjevs4sk6f5mcmjw56fj70gag9xkg6e8tmn9fj842pkfgf8glsh83z9t
