### ISSUE TITLE
display ZS version number

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#75]
display ZS version number in easily findable location - for instance, at bottom of side menu, or in settings view

**Comment by franzaps** [comment]
You can go to your installed apps list (update screen) and see it there right?

**Comment by alltheseas** [comment]
> You can go to your installed apps list (update screen) and see it there right?

yes - it displays

**Comment by franzaps** [comment]
Include in the bottom sidebar as well

**Comment by alltheseas** [comment]
this is impleneted in 0.1.13
