### ISSUE TITLE
revisit log in UI

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#76]
_what happens_

for me, log in UI is not clear in top left menu that inputting a NIP-05, or npub is expected, and that there is a text input field to the left of the log in button

_suggestion_

consider adding placeholder text where the text input field is

![image](https://github.com/zapstore/zapstore/assets/64376233/a1ce6826-e45d-4a5d-b9d2-871939d60162)

**Comment by alltheseas** [comment]
`android:hint="Enter NIP-05 (e.g. fran@zap.store, or npub123etc.."` 

https://stackoverflow.com/questions/8221072/android-add-placeholder-text-to-edittext

**Comment by franzaps** [comment]
Thanks for that, but we're using Flutter! This was fixed yesterday before release
