### ISSUE TITLE
Integrate with mobifree?

### ISSUE THREAD

**Issue by franzaps** [zapstore/zapstore#78]
https://mobifree.org/

@alltheseas you had shared this one with me but came across it again on the F-Droid website. Their positioning against Big Tech is positive but have no problem in glorifying the corrupt european institutions. Cringe but worth checking out actually how many users they reach with their e/OS and eventually try to get zs on there.

**Comment by alltheseas** [comment]
apparenetly mobifree is a poorly communicated EU grant program, and not an OS 

https://cordis.europa.eu/project/id/101135795
