### ISSUE TITLE
Alpha Dev Customers

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#8]
### What signature method do devs use to sign their Android app

-first check github
-as needed, ask exploration open ended questions on PGP/cert/NIP-69, bunker, or some other authentication method etc.

1. Vitor / Amethyst (uses actions and shares secrets with github) @fr4nzap
2. Miljan / Primal (uses actions and shares secrets with github) @alltheseas to confirm =>
3. Amber / GreenArt (uses actions and shares secrets with github) @fr4nzap 
4. Mutiny / Tony/Ben/Paul (uses actions and shares secrets with github) @fr4nzap 
5. Blixt - @alltheseas No
6. Minibits (uses actions and shares secrets with codepush - also from microsoft) @fr4nzap 
7. Nostrband - @fr4nzap 
8. 0xChat - @alltheseas No
9. SimpleX (unsure, appears to be signing on local device? need to ask) @alltheseas No
10. Zeus (unsure, appears to be signing on local device but has build action? need to ask) @alltheseas No

Other apps after these: https://primal.net/e/note1a3wt62zht0v8yfhy27g68ctzt62z3wfk68g6rvcu0cs07vw0rycsxtnyfc

### 69 spec - PGP/cert <-> nsec NIP-69 draft
@fr4nzap to publish draft
@alltheseas to create simple flow chart

**Comment by alltheseas** [comment]
Amber
![Screenshot from 2024-04-17 11-18-49](https://github.com/zapstore/zapstore/assets/64376233/309c3041-01d8-4bc3-9165-9f1ec0b29be6)

Blixt cannot find create release yml

0xChat  cannot find create release yml

SimpleX  cannot find create release yml

ZeusLN cannot find create release yml, although there is a build yml

![Screenshot from 2024-04-17 11-23-23](https://github.com/zapstore/zapstore/assets/64376233/507f8e33-72b5-436c-b260-cb38eb9f7925)

**Comment by fr4nzap** [comment]
In 2-3 hours will have the developers landing page up

**Comment by fr4nzap** [comment]
https://zap.store/developers

**Comment by franzaps** [comment]
We now have a better idea of the path forward, closing

**Comment by schildbach** [comment]
I build and sign apps (APKs) on an airgapped devices only, and specifically _not_ in any kind of cloud. Does zapstore support this for devs?

**Comment by franzaps** [comment]
@schildbach Sure, use `-a` to publish a local package. https://github.com/zapstore/zapstore-cli/?tab=readme-ov-file#publishing-a-package
