### ISSUE TITLE
multi-sig release

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#80]
## user story

As a team of devs developing one app, we would like to set up a multi-sig quorum to sign releases, so that we distribute signing responsibilities & risk.

### acceptance criteria
1. devs can set up quorum m of n multi-sig for signing releases

### questions
1. what happens if a dev retires, or steps away?

### context
see https://njump.me/nevent1qqs8pmmae89agph80928l6gjm0wymechqazv80jwqrqy4cgk08epjacrrnpt0
see https://github.com/nickfarrow/frostr

**Comment by franzaps** [comment]
Shouldn't we leave these things to emerge from users? Maybe there's little demand

**Comment by alltheseas** [comment]
Fair. Let me add a new label - unvalidated

**Comment by franzaps** [comment]
Sure is there value in collecting issues that may never be implemented?

**Comment by franzaps** [comment]
How about having ONE issue where we add these unvalidated ideas?  A lot of them adds clutter when trying to find the important stuff

**Comment by alltheseas** [comment]
> How about having ONE issue where we add these unvalidated ideas? A lot of them adds clutter when trying to find the important stuff

OK

https://github.com/zapstore/zapstore/issues/105
