### ISSUE TITLE
zap.store causing OS to freeze?

### ISSUE THREAD

**Issue by franzaps** [zapstore/zapstore#91]
A user reported that 
 - downloaded the app a few weeks ago
 - maybe a minute or so after I opened it it froze my phone; had to hold down the power button to regain use of phone
 - deleted the app after my phone restarted
 - Downloaded it again today and everything was kinda slow to load but I was able to install the weather app. After that phone froze again. Had to restart
 - Opened the app again and it froze my phone basically instantly
 - Restarted my phone and deleted the app

[Galaxy S24 Ultra, Android 14]

**Comment by alltheseas** [comment]
Are there crash logs @franzaps ?

**Comment by franzaps** [comment]
Probably but we need to get them out of the device. Will have to look at a way to send crash reports and also one of these cloud services to test the app on a trillion devices

**Comment by alltheseas** [comment]
https://github.com/zapstore/zapstore/issues/92

**Comment by alltheseas** [comment]
https://github.com/zapstore/zapstore/issues/93

**Comment by franzaps** [comment]
Impossible to reproduce, closing in favor of #92
