### ISSUE TITLE
Blank categories and releases

### ISSUE THREAD

**Issue by franzaps** [zapstore/zapstore#94]
![v](https://github.com/zapstore/zapstore/assets/126621043/38401204-b92d-4d20-afa0-d0770edd4eaf)

**Comment by franzaps** [comment]
The skeleton you see there is the "loading" animation... yes it's a loading state that never resolves

**Comment by alltheseas** [comment]
> The skeleton you see there is the "loading" animation... yes it's a loading state that never resolves

You understand this, but will a newcomer to ZS? 

cc @NielLiesmons

**Comment by franzaps** [comment]
I don't quite understand your concern. Skeletons are a design pattern that's well established and used everywhere

This bug is about a failure to exit that state and display actual data

**Comment by alltheseas** [comment]
I experienced a prolonged wait time, and was not sure the skeleton was a loading animation indicating progress. I had doubts that there was progress being made under the hood. 

This felt like a mini-anxiety moment. 

It is possible this is only experienced by me.

**Comment by franzaps** [comment]
Ok got it. Related to #83 

(we could make the animation more prolonged and you should only see this when the local database is empty)

**Comment by franzaps** [comment]
should report via #37

**Comment by franzaps** [comment]
Tried with different screen sizes but can't reproduce. For sure that blank area is a red screen during Flutter development, and a stacktrace is being thrown. Should be caught by our error handler and reported. See #37
