### ISSUE TITLE
Allow for revert to older app version

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#96]
https://njump.me/note1d9vsrutzqw622ny7h4t05qa3gl0aapmhqwcsqmuu3q42z9sz7zfqf0qdsv

**Comment by franzaps** [comment]
This is not possible on Android (short of removing the app and reinstalling) as it's restricted by the operating system

**Comment by alltheseas** [comment]
On iOS Testflight allows this. Android has no such functionality?

**Comment by franzaps** [comment]
It's considered dangerous from a security standpoint, probably why Apple only allows it on Testflight. But no, afaik not possible
