### ISSUE TITLE
Add warning if project is non-FOSS

### ISSUE THREAD

**Issue by franzaps** [zapstore/zapstore#97]
This for when we support other sources than github

**Comment by alltheseas** [comment]
> Maybe a “⚠️warning: closed source ⚠️” label. 

The source code cannot be audited, or verified. By using this app you sign up to a greater risk of rugpull, and uncertainty in what happens with your data. 

![image](https://github.com/zapstore/zapstore/assets/64376233/8fc9e057-5f8f-48e3-828d-5157874bdf43)

**Comment by franzaps** [comment]
Developers who self-sign closed-source apps will have to include a flag in `zapstore publish`

https://github.com/zapstore/zapstore-cli/issues/8

**Comment by franzaps** [comment]
Based on presence/absence of `repository`

**Comment by franzaps** [comment]
Fixed in 745e5f6b0c796ce7635359f6b7fd77294bbf1542
